services:
  anki-sync-server:
    build: .
    container_name: anki-sync-server
    network_mode: host  
    volumes:
      - ./data:/app/data
      - ./anki-bundled:/app/anki-bundled
      - ./ankisyncd.conf:/app/ankisyncd.conf
    restart: unless-stopped
